"""initial database migration

Revision ID: d3147d44baf5
Revises: 
Create Date: 2020-05-05 13:12:23.574279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3147d44baf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_date_time', sa.DateTime(), nullable=False),
    sa.Column('entry_title', sa.String(length=100), nullable=False),
    sa.Column('entry_desc', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_desc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diary_entry')
    # ### end Alembic commands ###
